version: "2"

services:
  talker:
    build: ./
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ros2 run kinemic_ros_bridge kinemic_ros_node
    depends_on:
      - listener

  listener:
    build: ./
    environment:
      - "PYTHONUNBUFFERED=1"
    command: ros2 run demo_nodes_py listener
